// Code generated by gen_boundproc.go. DO NOT EDIT.

package wincoe

import (
	"fmt"
	"syscall"

	"golang.org/x/sys/windows"
)

// ----------------------------------------------------------------------------
// Arity 0
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks0 interface {
	Name() string
	Call() (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc0 struct {
	*windows.LazyProc
}

func (r *realLazyProc0) Name() string {
	return r.LazyProc.Name
}

func (r *realLazyProc0) Call() (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr())
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc0(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks0 {
	if dll == nil {
		panic2("MustLoadProc0: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc0: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc0{LazyProc: lp}
}

type BoundProc0 struct {
	Proc  LazyProcishWrapperForMocks0
	Check WinCheckFunc
}

func (b *BoundProc0) Call() WinResult {
	return WinCall0(b.Proc, b.Check)
}

func (b *BoundProc0) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc0:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc0(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc0 {
	if check == nil {
		panic2("NewBoundProc0: nil WinCheckFunc passed as arg")
	}
	return &BoundProc0{
		Proc:  MustLoadProc0(dll, name),
		Check: check,
	}
}

func WinCall0(proc LazyProcishWrapperForMocks0, check WinCheckFunc) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call()
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 1
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks1 interface {
	Name() string
	Call(a1 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc1 struct {
	*windows.LazyProc
}

func (r *realLazyProc1) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc1) Call(a1 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc1(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks1 {
	if dll == nil {
		panic2("MustLoadProc1: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc1: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc1{LazyProc: lp}
}

type BoundProc1 struct {
	Proc  LazyProcishWrapperForMocks1
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc1) Call(a1 uintptr) WinResult {
	return WinCall1(b.Proc, b.Check, a1)
}

func (b *BoundProc1) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc1:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc1(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc1 {
	if check == nil {
		panic2("NewBoundProc1: nil WinCheckFunc passed as arg")
	}
	return &BoundProc1{
		Proc:  MustLoadProc1(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall1(proc LazyProcishWrapperForMocks1, check WinCheckFunc, a1 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1)
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 2
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks2 interface {
	Name() string
	Call(a1, a2 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc2 struct {
	*windows.LazyProc
}

func (r *realLazyProc2) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc2) Call(a1, a2 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1, a2)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc2(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks2 {
	if dll == nil {
		panic2("MustLoadProc2: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc2: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc2{LazyProc: lp}
}

type BoundProc2 struct {
	Proc  LazyProcishWrapperForMocks2
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc2) Call(a1, a2 uintptr) WinResult {
	return WinCall2(b.Proc, b.Check, a1, a2)
}

func (b *BoundProc2) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc2:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc2(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc2 {
	if check == nil {
		panic2("NewBoundProc2: nil WinCheckFunc passed as arg")
	}
	return &BoundProc2{
		Proc:  MustLoadProc2(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall2(proc LazyProcishWrapperForMocks2, check WinCheckFunc, a1, a2 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1, a2)
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 3
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks3 interface {
	Name() string
	Call(a1, a2, a3 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc3 struct {
	*windows.LazyProc
}

func (r *realLazyProc3) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc3) Call(a1, a2, a3 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1, a2, a3)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc3(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks3 {
	if dll == nil {
		panic2("MustLoadProc3: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc3: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc3{LazyProc: lp}
}

type BoundProc3 struct {
	Proc  LazyProcishWrapperForMocks3
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc3) Call(a1, a2, a3 uintptr) WinResult {
	return WinCall3(b.Proc, b.Check, a1, a2, a3)
}

func (b *BoundProc3) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc3:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc3(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc3 {
	if check == nil {
		panic2("NewBoundProc3: nil WinCheckFunc passed as arg")
	}
	return &BoundProc3{
		Proc:  MustLoadProc3(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall3(proc LazyProcishWrapperForMocks3, check WinCheckFunc, a1, a2, a3 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1, a2, a3)
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 4
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks4 interface {
	Name() string
	Call(a1, a2, a3, a4 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc4 struct {
	*windows.LazyProc
}

func (r *realLazyProc4) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc4) Call(a1, a2, a3, a4 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1, a2, a3, a4)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc4(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks4 {
	if dll == nil {
		panic2("MustLoadProc4: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc4: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc4{LazyProc: lp}
}

type BoundProc4 struct {
	Proc  LazyProcishWrapperForMocks4
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc4) Call(a1, a2, a3, a4 uintptr) WinResult {
	return WinCall4(b.Proc, b.Check, a1, a2, a3, a4)
}

func (b *BoundProc4) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc4:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc4(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc4 {
	if check == nil {
		panic2("NewBoundProc4: nil WinCheckFunc passed as arg")
	}
	return &BoundProc4{
		Proc:  MustLoadProc4(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall4(proc LazyProcishWrapperForMocks4, check WinCheckFunc, a1, a2, a3, a4 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1, a2, a3, a4)
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 5
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks5 interface {
	Name() string
	Call(a1, a2, a3, a4, a5 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc5 struct {
	*windows.LazyProc
}

func (r *realLazyProc5) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc5) Call(a1, a2, a3, a4, a5 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1, a2, a3, a4, a5)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc5(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks5 {
	if dll == nil {
		panic2("MustLoadProc5: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc5: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc5{LazyProc: lp}
}

type BoundProc5 struct {
	Proc  LazyProcishWrapperForMocks5
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc5) Call(a1, a2, a3, a4, a5 uintptr) WinResult {
	return WinCall5(b.Proc, b.Check, a1, a2, a3, a4, a5)
}

func (b *BoundProc5) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc5:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc5(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc5 {
	if check == nil {
		panic2("NewBoundProc5: nil WinCheckFunc passed as arg")
	}
	return &BoundProc5{
		Proc:  MustLoadProc5(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall5(proc LazyProcishWrapperForMocks5, check WinCheckFunc, a1, a2, a3, a4, a5 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1, a2, a3, a4, a5)
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 6
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks6 interface {
	Name() string
	Call(a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc6 struct {
	*windows.LazyProc
}

func (r *realLazyProc6) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc6) Call(a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1, a2, a3, a4, a5, a6)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc6(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks6 {
	if dll == nil {
		panic2("MustLoadProc6: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc6: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc6{LazyProc: lp}
}

type BoundProc6 struct {
	Proc  LazyProcishWrapperForMocks6
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc6) Call(a1, a2, a3, a4, a5, a6 uintptr) WinResult {
	return WinCall6(b.Proc, b.Check, a1, a2, a3, a4, a5, a6)
}

func (b *BoundProc6) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc6:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc6(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc6 {
	if check == nil {
		panic2("NewBoundProc6: nil WinCheckFunc passed as arg")
	}
	return &BoundProc6{
		Proc:  MustLoadProc6(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall6(proc LazyProcishWrapperForMocks6, check WinCheckFunc, a1, a2, a3, a4, a5, a6 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1, a2, a3, a4, a5, a6)
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 7
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks7 interface {
	Name() string
	Call(a1, a2, a3, a4, a5, a6, a7 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc7 struct {
	*windows.LazyProc
}

func (r *realLazyProc7) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc7) Call(a1, a2, a3, a4, a5, a6, a7 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1, a2, a3, a4, a5, a6, a7)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc7(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks7 {
	if dll == nil {
		panic2("MustLoadProc7: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc7: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc7{LazyProc: lp}
}

type BoundProc7 struct {
	Proc  LazyProcishWrapperForMocks7
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc7) Call(a1, a2, a3, a4, a5, a6, a7 uintptr) WinResult {
	return WinCall7(b.Proc, b.Check, a1, a2, a3, a4, a5, a6, a7)
}

func (b *BoundProc7) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc7:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc7(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc7 {
	if check == nil {
		panic2("NewBoundProc7: nil WinCheckFunc passed as arg")
	}
	return &BoundProc7{
		Proc:  MustLoadProc7(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall7(proc LazyProcishWrapperForMocks7, check WinCheckFunc, a1, a2, a3, a4, a5, a6, a7 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1, a2, a3, a4, a5, a6, a7)
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 8
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks8 interface {
	Name() string
	Call(a1, a2, a3, a4, a5, a6, a7, a8 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc8 struct {
	*windows.LazyProc
}

func (r *realLazyProc8) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc8) Call(a1, a2, a3, a4, a5, a6, a7, a8 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1, a2, a3, a4, a5, a6, a7, a8)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc8(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks8 {
	if dll == nil {
		panic2("MustLoadProc8: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc8: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc8{LazyProc: lp}
}

type BoundProc8 struct {
	Proc  LazyProcishWrapperForMocks8
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc8) Call(a1, a2, a3, a4, a5, a6, a7, a8 uintptr) WinResult {
	return WinCall8(b.Proc, b.Check, a1, a2, a3, a4, a5, a6, a7, a8)
}

func (b *BoundProc8) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc8:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc8(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc8 {
	if check == nil {
		panic2("NewBoundProc8: nil WinCheckFunc passed as arg")
	}
	return &BoundProc8{
		Proc:  MustLoadProc8(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall8(proc LazyProcishWrapperForMocks8, check WinCheckFunc, a1, a2, a3, a4, a5, a6, a7, a8 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1, a2, a3, a4, a5, a6, a7, a8)
	return makeWinResult(op, check, r1, r2, callStatus)
}

// ----------------------------------------------------------------------------
// Arity 9
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks9 interface {
	Name() string
	Call(a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc9 struct {
	*windows.LazyProc
}

func (r *realLazyProc9) Name() string {
	return r.LazyProc.Name
}

//go:uintptrescapes
func (r *realLazyProc9) Call(a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(), a1, a2, a3, a4, a5, a6, a7, a8, a9)
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc9(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks9 {
	if dll == nil {
		panic2("MustLoadProc9: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc9: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc9{LazyProc: lp}
}

type BoundProc9 struct {
	Proc  LazyProcishWrapperForMocks9
	Check WinCheckFunc
}

//go:uintptrescapes
func (b *BoundProc9) Call(a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) WinResult {
	return WinCall9(b.Proc, b.Check, a1, a2, a3, a4, a5, a6, a7, a8, a9)
}

func (b *BoundProc9) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc9:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc9(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc9 {
	if check == nil {
		panic2("NewBoundProc9: nil WinCheckFunc passed as arg")
	}
	return &BoundProc9{
		Proc:  MustLoadProc9(dll, name),
		Check: check,
	}
}

//go:uintptrescapes
func WinCall9(proc LazyProcishWrapperForMocks9, check WinCheckFunc, a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call(a1, a2, a3, a4, a5, a6, a7, a8, a9)
	return makeWinResult(op, check, r1, r2, callStatus)
}
