//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const procTemplate = `// Code generated by gen_boundproc.go. DO NOT EDIT.

package wincoe

import (
	"fmt"
	"syscall"
	
	"golang.org/x/sys/windows"
)

{{range .}}
// ----------------------------------------------------------------------------
// Arity {{.Suffix}}
// ----------------------------------------------------------------------------

// LazyProcishWrapperForMocks{{.Suffix}} is the minimal interface that WinCall{{.Suffix}} needs from a windows.LazyProc-like object.
//
// We deliberately avoid the full *windows.LazyProc type to enable mocking.
type LazyProcishWrapperForMocks{{.Suffix}} interface {
	// Name returns the name of the procedure (used in error messages).
	//Why Name() instead of a field? Because interfaces in Go cannot require fields — only methods
	Name() string

	// Call invokes the Windows procedure with the given arguments.
	// Signature must match windows.LazyProc.Call exactly.
	Call({{.InterfaceArgs}}) (r1, r2 uintptr, lastErr error)

	Find() error
	Addr() uintptr
}

// realLazyProc{{.Suffix}} wraps *windows.LazyProc to satisfy interface LazyProcishWrapperForMocks{{.Suffix}}.
//
// Embedding gives us .Find() and .Addr() for free via promotion from *windows.LazyProc.
// .Name() and .Call() below are explicitly overridden (not promoted): .Name() adapts the
// embedded field's Name string into the interface's Name() string method, and .Call() bypasses
// windows.LazyProc.Call() entirely to invoke syscall.SyscallN directly{{if .IsVariadic}} (this suffix
// still incurs the usual 1-allocation variadic-slice cost, since args...uintptr's length isn't known
// at compile time){{else}} for the zero-allocation fixed-arity path (see .Call's own doc comment below){{end}}.
type realLazyProc{{.Suffix}} struct {
	*windows.LazyProc
}

// Name implements LazyProcishWrapperForMocks{{.Suffix}}.
//
// Returns the procedure name for use in error messages.
func (r *realLazyProc{{.Suffix}}) Name() string {
	return r.LazyProc.Name
}

{{.EscapeDirective}}
func (r *realLazyProc{{.Suffix}}) Call({{.InterfaceArgs}}) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete(or variadic) arguments triggers a Go 1.18+ 
	// compiler intrinsic that entirely avoids variadic slice allocation because SyscallN is compiler-special.
	// so zero allocations instead of 1 of 8 bytes which LazyProc.Call(..) would cause
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(){{if .CallArgs}}, {{.CallArgs}}{{end}})
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

// MustLoadProc{{.Suffix}} eagerly resolves a procedure from the given DLL and wraps it into a LazyProcishWrapperForMocks{{.Suffix}}.
// it loads the DLL and resolves the proc, so it unlazifies the whole thing, thus it can panic if DLL or proc cannot be loaded or found
//
// It is a thin, validated convenience over dll.NewProc(name) + LazyLoadProc{{.Suffix}}, which wraps the
// resulting *windows.LazyProc into realLazyProc{{.Suffix}} directly (no separate RealProc/BindFunc layer exists).
// This function enforces basic invariants early:
//   - dll must be non-nil
//
// The returned LazyProcishWrapperForMocks{{.Suffix}} is suitable for use directly with WinCall{{.Suffix}},
// or wrapped into a BoundProc{{.Suffix}} via NewBoundProc{{.Suffix}}/NewLazyBoundProc{{.Suffix}} for a
// permanently-attached failure-checking strategy.
//
// MustLoadProc{{.Suffix}} does NOT attach any failure semantics (WinCheckFunc). Callers must
// explicitly provide the appropriate check strategy (e.g. CheckBool, CheckHandle)
// when invoking the procedure via WinCall{{.Suffix}} or when binding it.
//
// Panics:
//   - if dll is nil
func MustLoadProc{{.Suffix}}(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks{{.Suffix}} {
	if dll == nil {
		panic2("MustLoadProc{{.Suffix}}: nil dll")
	}
	loadDll(dll) // make it non-lazy, load it now if not loaded! or panic if loading fails!

	proc := LazyLoadProc{{.Suffix}}(dll, name)

	// Force resolution now. Find() returns nil on success (the address is then
	// available via proc.Addr()) or a non-nil error if resolution failed.
	if err := proc.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc{{.Suffix}}: unable to find windows API function named %q actual %q, err: %v", name, proc.Name(), err.Error()))
	}

	return proc
}

// LazyLoadProc{{.Suffix}} lazily wraps a procedure from the given DLL into a LazyProcishWrapperForMocks{{.Suffix}}
// without loading the DLL or resolving the symbol eagerly.
//
// Use this for optional Windows APIs that may not exist on older Windows versions.
//
// Panics:
//   - if dll is nil
func LazyLoadProc{{.Suffix}}(
	dll *windows.LazyDLL,
	name string,
) LazyProcishWrapperForMocks{{.Suffix}} {
	if dll == nil {
		panic2("LazyLoadProc{{.Suffix}}: nil dll")
	}
	validateProcNameString(name)
	lp := dll.NewProc(name)
	if lp == nil {
		panic2(fmt.Sprintf("BUG: unexpected in LazyLoadProc{{.Suffix}}: LazyProc was nil for proc %q in dll %v", name, dll))
	}
	
	rlp := &realLazyProc{{.Suffix}}{LazyProc: lp}

	// Validate the concrete wrapper too, so implementations remain subject to
	// the same invariant even if their Name method changes independently.
	validateProcName(rlp)

	return rlp
}

// BoundProc{{.Suffix}} represents a Windows API procedure permanently bound to a
// specific failure-checking strategy.
//
// It wraps a LazyProcishWrapperForMocks{{.Suffix}} (usually a windows.LazyProc or a mock for tests) and a WinCheckFunc.
// By using BoundProc{{.Suffix}} instead of raw Syscall/Call, you centralize error
// handling logic for the specific API{{if .EscapeDirective}} while maintaining the ability to
// use {{.EscapeDirective}} for memory safety{{end}}.
type BoundProc{{.Suffix}} struct {
	proc  LazyProcishWrapperForMocks{{.Suffix}}
	check WinCheckFunc
}

// Call executes the underlying Windows procedure with the provided arguments.
//
{{if .EscapeDirective}}// SECURITY WARNING: This method uses the {{.EscapeDirective}} compiler directive.
// To ensure memory safety and prevent "0xc0000005 Access Violation" crashes,
// any Go pointer passed as an argument MUST be converted to uintptr using
// uintptr(unsafe.Pointer(&x)) directly within the argument list of the
// call site.
// So {{.EscapeDirective}} = escape to heap + keep-alive for the duration of the call.
// The compiler inserts the necessary liveness (equivalent to an implicit KeepAlive across the entire function call)
// for any argument passed as uintptr(unsafe.Pointer(...)) to a function marked {{.EscapeDirective}}.
//
// Example:
//
//	var size uint32
//	proc.Call(handle, uintptr(unsafe.Pointer(&size)))
//
// This direct conversion signals the Go compiler to move the variable to
// the heap, ensuring its memory address remains stable even if the stack grows.
{{else}}// This arity ({{.Suffix}}) takes no arguments at all, so there is nothing that
// could alias a Go pointer and no need for an escape-pinning compiler directive here.
{{end}}//
{{if .EscapeDirective}}{{.EscapeDirective}}
{{end}}func (b *BoundProc{{.Suffix}}) Call({{.InterfaceArgs}}) WinResult {
	return internalWinCall{{.Suffix}}(b.proc, b.check{{if .CallArgs}}, {{.CallArgs}}{{end}})
}

// Find attempts to locate the procedure in the DLL.
// Returns nil if the procedure is successfully found, or an error if it is not.
func (b *BoundProc{{.Suffix}}) Find() error {
	if err := b.proc.Find(); err != nil {
		return fmt.Errorf("BoundProc{{.Suffix}}:Find says that LazyProcishWrapperForMocks{{.Suffix}}/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

// NewBoundProc{{.Suffix}} initializes a BoundProc{{.Suffix}} by resolving a procedure from the
// provided DLL and attaching a result-checking function.
// It eagerly resolves the DLL and proc's address so it won't have to do it on the first .Call(..)
{{if .IsVariadic}}// Each .Call(..) causes 1 heap alloc of 8 bytes due to the variadic args slice, just like LazyProc.Call(..) does!
{{else}}// Each .Call(..) causes ZERO heap allocations: the fixed-arity args are passed directly to
// syscall.SyscallN, which the Go 1.18+ compiler recognizes as a special intrinsic and thus never
// builds a variadic slice for, unlike LazyProc.Call(..) (see realLazyProc{{.Suffix}}.Call's doc comment).
{{end}}//
// Parameters:
//   - dll: A pointer to a windows.LazyDLL (e.g., kernel32, user32).
//   - name: The exact string name of the procedure (e.g., "GetProcessId").
//   - check: A WinCheckFunc (e.g., CheckBool) used to determine if the
//     API call failed based on its return value.
//
// It panics if the check function is nil.
func NewBoundProc{{.Suffix}}(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc{{.Suffix}} {
	if check == nil {
		panic2("NewBoundProc{{.Suffix}}: nil WinCheckFunc passed as arg")
	}
	return &BoundProc{{.Suffix}}{
		proc:  MustLoadProc{{.Suffix}}(dll, name),
		check: check,
	}
}

// NewLazyBoundProc{{.Suffix}} initializes a BoundProc{{.Suffix}} without eagerly resolving the procedure or DLL.
// DLL loading and symbol resolution are deferred until the first .Find() or .Call(...) invocation.
// Use this for optional Windows APIs that may not exist on older Windows versions.
//
// Panics:
//   - if check is nil
//   - if dll is nil
func NewLazyBoundProc{{.Suffix}}(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc{{.Suffix}} {
	if check == nil {
		panic2("NewLazyBoundProc{{.Suffix}}: nil WinCheckFunc passed as arg")
	}
	return &BoundProc{{.Suffix}}{
		proc:  LazyLoadProc{{.Suffix}}(dll, name),
		check: check,
	}
}

// WinCall{{.Suffix}} is the low-level engine that executes the syscall and performs
// automated error checking.
//
{{if .EscapeDirective}}// It leverages {{.EscapeDirective}} to signal to the compiler that arguments
// may be pointers converted to integers.{{else}}// This arity ({{.Suffix}}) takes no arguments, so there are none that could be
// pointers converted to integers and no compiler directive is needed here.{{end}} It calls the procedure, captures
// the return values (r1, r2) and the system error (the third return value, which is
// GetLastError(); Go's runtime clears thread-local error state via SetLastError(0)
// immediately before the syscall and captures GetLastError() immediately after, as a
// single atomic/unpreemptible unit performed by syscall.SyscallN — see
// WinResult.CallStatus's doc comment in main_api.go and
// https://github.com/golang/go/issues/41220), then passes them to
// CheckWinResult to produce a clean Go error if the call failed.
//
{{if .EscapeDirective}}// WARNING: you must do the uintptr casting at the args call place (for pointers on stack!) for this to work and not crash randomly because the stack got moved by Go.
// The price of absolute memory safety in Go is that you must write uintptr(unsafe.Pointer(...)) explicitly at the exact call site.
// This tells the compiler, "Pin this variable right now."
//
{{end}}// Use this directly only if you need to bypass the BoundProc abstraction.
// Otherwise, use BoundProc.Call for better type organization.
//
{{if .EscapeDirective}}{{.EscapeDirective}}
{{end}}func WinCall{{.Suffix}}(proc LazyProcishWrapperForMocks{{.Suffix}}, check WinCheckFunc{{if .InterfaceArgs}}, {{.InterfaceArgs}}{{end}}) WinResult {
	validateProcName(proc)
	// pname:=proc.Name()
	// if name != pname {
	// 	panic2(fmt.Sprintf("BUG: proc name %q is different than validated proc name %q and it didn't fail earlier!", pname, name))
	// }
	return internalWinCall{{.Suffix}}(proc, check, {{.CallArgs}})
}

{{.EscapeDirective}}
func internalWinCall{{.Suffix}}(proc LazyProcishWrapperForMocks{{.Suffix}}, check WinCheckFunc{{if .InterfaceArgs}}, {{.InterfaceArgs}}{{end}}) WinResult {
	r1, r2, callStatus := proc.Call({{.CallArgs}}) // proc.Call here is realLazyProc{{.Suffix}}.Call in production, which calls syscall.SyscallN directly (NOT windows.LazyProc.Call); this indirection through the LazyProcishWrapperForMocks{{.Suffix}} interface exists purely so tests can substitute a mock{{if .IsVariadic}}; so this means it will do a total of 1 alloc of 8 bytes for the variadic slice of args(The only allocation happens at the very top call site when the user calls BoundProcN.Call(a, b, c)){{end}}
	return makeWinResult(proc.Name(), check, r1, r2, callStatus)
}
{{end}}
`

type ProcData struct {
	Suffix          string // "N", "0", "1", "2", etc.
	InterfaceArgs   string // "args ...uintptr" vs "a1, a2 uintptr"
	CallArgs        string // "args..." vs "a1, a2"
	EscapeDirective string
	IsVariadic      bool
}

const TheEscapeDirective = "//go:uintptrescapes"

func writeFileAtomically(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)

	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("create temporary output file: %w", err)
	}

	tmpName := tmp.Name()
	removeTemp := true
	defer func() {
		if removeTemp {
			_ = os.Remove(tmpName)
		}
	}()

	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("chmod temporary output file: %w", err)
	}
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temporary output file: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sync temporary output file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temporary output file: %w", err)
	}

	// os.Rename replaces an existing regular file atomically on Unix.
	// On supported Windows versions Go uses the platform replacement
	// behavior available to it. The temporary file lives in the same
	// directory, so the operation never crosses filesystems.
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("replace generated output file: %w", err)
	}

	removeTemp = false
	return nil
}

func main() {
	var data []ProcData

	// 1. Manually inject the variadic "N" case first
	data = append(data, ProcData{
		Suffix:          "N",
		InterfaceArgs:   "args ...uintptr",
		CallArgs:        "args...",
		EscapeDirective: TheEscapeDirective,
		IsVariadic:      true,
	})

	// 2. Loop through the fixed arities (0 to 9)
	for i := 0; i <= 12; i++ {
		var args, callArgs []string
		for j := 1; j <= i; j++ {
			args = append(args, fmt.Sprintf("a%d", j))
			callArgs = append(callArgs, fmt.Sprintf("a%d", j))
		}

		argsStr := ""
		if i > 0 {
			argsStr = strings.Join(args, ", ") + " uintptr"
		}

		directive := ""
		if i > 0 {
			directive = TheEscapeDirective
		}

		data = append(data, ProcData{
			Suffix:          fmt.Sprintf("%d", i),
			InterfaceArgs:   argsStr,
			CallArgs:        strings.Join(callArgs, ", "),
			EscapeDirective: directive,
			IsVariadic:      false,
		})
	}

	tmpl, err := template.New("procs").Parse(procTemplate)
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		panic(err)
	}

	// Format the generated code natively so it's clean
	formatted, err := format.Source(buf.Bytes())
	// if err != nil {
	// 	fmt.Println("Code generation succeeded but formatting failed. Check the syntax.")
	// 	os.WriteFile("boundproc_gen.go", buf.Bytes(), 0644)
	// 	panic(err)
	// }
	if err != nil {
		const diagnosticPath = "boundproc_gen.unformatted.go.txt"
		writeErr := writeFileAtomically(diagnosticPath, buf.Bytes(), 0o644)
		if writeErr != nil {
			panic(fmt.Errorf(
				"format generated source: %w; additionally failed to write %s: %v",
				err,
				diagnosticPath,
				writeErr,
			))
		}
		panic(fmt.Errorf(
			"format generated source: %w; unformatted output written to %s",
			err,
			diagnosticPath,
		))
	}

	if err := writeFileAtomically("boundproc_gen.go", formatted, 0o644); err != nil {
		panic(fmt.Errorf("write generated source: %w", err))
	}

	fmt.Println("Successfully generated&formatted boundproc_gen.go")
}
