//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

const procTemplate = `// Code generated by gen_boundproc.go. DO NOT EDIT.

package wincoe

import (
	"fmt"
	"syscall"
	
	"golang.org/x/sys/windows"
)

{{range .}}
// ----------------------------------------------------------------------------
// Arity {{.N}}
// ----------------------------------------------------------------------------

type LazyProcishWrapperForMocks{{.N}} interface {
	Name() string
	Call({{.Args}}) (r1, r2 uintptr, lastErr error)
	Find() error
	Addr() uintptr
}

type realLazyProc{{.N}} struct {
	*windows.LazyProc
}

func (r *realLazyProc{{.N}}) Name() string {
	return r.LazyProc.Name
}

{{.EscapeDirective}}func (r *realLazyProc{{.N}}) Call({{.Args}}) (r1, r2 uintptr, lastErr error) {
	// Calling syscall.SyscallN directly with discrete arguments triggers a Go 1.18+ 
	// compiler intrinsic that entirely avoids variadic slice allocation.
	r1, r2, errno := syscall.SyscallN(r.LazyProc.Addr(){{if .CallArgs}}, {{.CallArgs}}{{end}})
	// SyscallN returns syscall.Errno, which satisfies the error interface.
	// CheckWinResult handles ERROR_SUCCESS (0) correctly as success.
	return r1, r2, errno
}

func MustLoadProc{{.N}}(dll *windows.LazyDLL, name string) LazyProcishWrapperForMocks{{.N}} {
	if dll == nil {
		panic2("MustLoadProc{{.N}}: nil dll")
	}
	loadDll(dll)
	lp := dll.NewProc(name)
	if err := lp.Find(); err != nil {
		panic2(fmt.Sprintf("MustLoadProc{{.N}}: unable to find windows API function named %q, err: %v", name, err.Error()))
	}
	return &realLazyProc{{.N}}{LazyProc: lp}
}

type BoundProc{{.N}} struct {
	Proc  LazyProcishWrapperForMocks{{.N}}
	Check WinCheckFunc
}

{{.EscapeDirective}}func (b *BoundProc{{.N}}) Call({{.Args}}) WinResult {
	return WinCall{{.N}}(b.Proc, b.Check{{if .CallArgs}}, {{.CallArgs}}{{end}})
}

func (b *BoundProc{{.N}}) Find() error {
	if err := b.Proc.Find(); err != nil {
		return fmt.Errorf("BoundProc{{.N}}:Find says that LazyProcish/LazyProc.Find() failed, err: %w", err)
	}
	return nil
}

func NewBoundProc{{.N}}(dll *windows.LazyDLL, name string, check WinCheckFunc) *BoundProc{{.N}} {
	if check == nil {
		panic2("NewBoundProc{{.N}}: nil WinCheckFunc passed as arg")
	}
	return &BoundProc{{.N}}{
		Proc:  MustLoadProc{{.N}}(dll, name),
		Check: check,
	}
}

{{.EscapeDirective}}func WinCall{{.N}}(proc LazyProcishWrapperForMocks{{.N}}, check WinCheckFunc{{if .Args}}, {{.Args}}{{end}}) WinResult {
	op := validateAndGetOp(proc)
	r1, r2, callStatus := proc.Call({{.CallArgs}})
	return makeWinResult(op, check, r1, r2, callStatus)
}
{{end}}
`

type ProcData struct {
	N               int
	Args            string
	CallArgs        string
	EscapeDirective string
}

func main() {
	var data []ProcData

	for i := 0; i <= 9; i++ {
		var args, callArgs []string
		for j := 1; j <= i; j++ {
			args = append(args, fmt.Sprintf("a%d", j))
			callArgs = append(callArgs, fmt.Sprintf("a%d", j))
		}

		argsStr := ""
		if i > 0 {
			argsStr = strings.Join(args, ", ") + " uintptr"
		}

		directive := ""
		if i > 0 {
			directive = "//go:uintptrescapes\n"
		}

		data = append(data, ProcData{
			N:               i,
			Args:            argsStr,
			CallArgs:        strings.Join(callArgs, ", "),
			EscapeDirective: directive,
		})
	}

	tmpl, err := template.New("procs").Parse(procTemplate)
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		panic(err)
	}

	// Format the generated code natively so it's clean
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("Code generation succeeded but formatting failed. Check the syntax.")
		os.WriteFile("boundproc_gen.go", buf.Bytes(), 0644)
		panic(err)
	}

	if err := os.WriteFile("boundproc_gen.go", formatted, 0644); err != nil {
		panic(err)
	}

	fmt.Println("Successfully generated boundproc_gen.go")
}
